apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: sharded
    namespace: openshift-ingress-operator
  spec:
    domain: apps-sharded.ocp.example.com
    routeSelector:
      matchLabels:
        istio: ingressgateway
    endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""