apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mysql-3
  namespace: ddbb
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: mysql-3:latest
      namespace: ddbb
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: examples/mysql-3/extend-image/
    git:
      ref: main
      uri: https://github.com/fperearodriguez/bookinfo-extddbb.git
    sourceSecret:
      name: MyAwesomeSecretName
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-3
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-3
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-3
              key: MYSQL_DATABASE
        - name: MYSQL_BOOKUSER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-3
              key: MYSQL_BOOKUSER
        - name: MYSQL_BOOKPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-3
              key: MYSQL_BOOKPASSWORD
      from:
        kind: ImageStreamTag
        name: mysql:8.0-el8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5